[project]
name = "diun-k8s-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "kubernetes>=32.0.1",
    "ruff>=0.11.11",
    "uvicorn>=0.34.2",
]
